import type { ModelCapabilities } from '@/types/provider/capabilities'

/**
 * Static capability declarations for all 22 providers.
 * This is the single source of truth for what each provider supports.
 */
export const PROVIDER_CAPABILITIES = {
  // ─── LLM Providers ───
  openai: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming', 'structuredOutput', 'vision'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['gpt-4.1-mini', 'gpt-4o-mini', 'gpt-4o', 'gpt-4.1', 'gpt-4.1-nano'],
  },
  deepseek: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['deepseek-chat'],
  },
  anthropic: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming', 'structuredOutput', 'vision'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['claude-sonnet-4-20250514', 'claude-3-5-haiku-20241022'],
  },
  gemini: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming', 'structuredOutput', 'vision', 'freeTier'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['gemini-2.5-flash', 'gemini-2.5-pro'],
  },
  groq: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming', 'freeTier'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant'],
  },
  mistral: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming', 'structuredOutput'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['mistral-large-latest', 'mistral-small-latest'],
  },
  cohere: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['command-r-plus', 'command-r'],
  },
  openrouter: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming', 'freeTier'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: [
      'meta-llama/llama-4-maverick:free',
      'deepseek/deepseek-chat-v3-0324:free',
    ],
  },
  ollama: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'localOnly'],
    requiresApiKey: false,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['deepseek-r1:8b', 'gemma3:1b', 'qwen3:0.6b', 'qwen3:8b', 'llama3.1:8b'],
  },
  xai: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['grok-2-latest', 'grok-3-mini'],
  },
  perplexity: {
    type: 'llm',
    features: ['translate', 'streaming'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: false,
    defaultModels: ['sonar', 'sonar-pro'],
  },
  cerebras: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming', 'freeTier'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['llama-3.3-70b', 'llama-3.1-8b'],
  },
  sambanova: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming', 'freeTier'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['Meta-Llama-3.3-70B-Instruct', 'Meta-Llama-3.1-8B-Instruct'],
  },
  together: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['meta-llama/Llama-3.3-70B-Instruct-Turbo'],
  },
  fireworks: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['accounts/fireworks/models/llama-v3p3-70b-instruct'],
  },
  zhipu: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['glm-4-flash', 'glm-4-plus'],
  },
  moonshot: {
    type: 'llm',
    features: ['translate', 'analyze', 'explain', 'streaming'],
    requiresApiKey: true,
    configurableBaseURL: true,
    maxBatchSize: 1,
    supportsRead: true,
    defaultModels: ['moonshot-v1-8k', 'moonshot-v1-32k'],
  },

  // ─── Pure HTTP Translate Providers ───
  google: {
    type: 'http-translate',
    features: ['translate', 'freeTier'],
    requiresApiKey: false,
    configurableBaseURL: false,
    maxBatchSize: 1,
    supportsRead: false,
    defaultModels: [],
  },
  microsoft: {
    type: 'http-translate',
    features: ['translate', 'freeTier'],
    requiresApiKey: false,
    configurableBaseURL: false,
    maxBatchSize: 1,
    supportsRead: false,
    defaultModels: [],
  },
  deepl: {
    type: 'http-translate',
    features: ['translate', 'batchTranslate'],
    requiresApiKey: true,
    configurableBaseURL: false,
    maxBatchSize: 50,
    supportsRead: false,
    defaultModels: [],
  },
  yandex: {
    type: 'http-translate',
    features: ['translate'],
    requiresApiKey: true,
    configurableBaseURL: false,
    maxBatchSize: 1,
    supportsRead: false,
    defaultModels: [],
  },
  baidu: {
    type: 'http-translate',
    features: ['translate'],
    requiresApiKey: true,
    configurableBaseURL: false,
    maxBatchSize: 1,
    supportsRead: false,
    defaultModels: [],
  },
} as const satisfies Record<string, ModelCapabilities>

export type ProviderId = keyof typeof PROVIDER_CAPABILITIES
